# See: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
edition = "2021"
newline_style = "unix"
tab_spaces = 2

match_block_trailing_comma = true
use_field_init_shorthand = true
use_try_shorthand = true
